/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.evancharlton.mileage;

public final class R {
    public static final class array {
        public static final int vehicles=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int add_fillup_btn=0x7f060005;
        public static final int amount_edit=0x7f060001;
        public static final int change_date_btn=0x7f060003;
        public static final int odometer_edit=0x7f060002;
        public static final int price_edit=0x7f060000;
        public static final int vehicle_spinner=0x7f060004;
    }
    public static final class layout {
        public static final int graphs=0x7f030000;
        public static final int history=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int add_fillup=0x7f050005;
        public static final int app_name=0x7f050000;
        public static final int custom_date=0x7f050004;
        public static final int fillup_history=0x7f050006;
        public static final int gallons=0x7f050002;
        public static final int graphs=0x7f050007;
        public static final int odometer=0x7f050003;
        public static final int price_per_gallon=0x7f050001;
    }
}
