/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.evancharlton.mileage;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int binary=0x7f020000;
        public static final int database=0x7f020001;
        public static final int gasbutton=0x7f020002;
        public static final int gasbutton_large=0x7f020003;
        public static final int gasbutton_psd=0x7f020004;
        public static final int gasbuttonx=0x7f020005;
        public static final int help=0x7f020006;
        public static final int help_xcf=0x7f020007;
        public static final int spreadsheet=0x7f020008;
        public static final int spreadsheet_document=0x7f020009;
    }
    public static final class id {
        public static final int about_app_btn=0x7f060012;
        public static final int add_fillup_btn=0x7f06001d;
        public static final int amount_edit=0x7f06000d;
        public static final int change_date_btn=0x7f06000f;
        public static final int close_about_btn=0x7f060001;
        public static final int close_help_btn=0x7f060013;
        public static final int export_csv_btn=0x7f06001c;
        public static final int export_db_btn=0x7f060018;
        public static final int export_sql_btn=0x7f06001a;
        public static final int help_container=0x7f060000;
        public static final int history_gallons=0x7f060014;
        public static final int history_price=0x7f060016;
        public static final int history_text2=0x7f060015;
        public static final int import_csv_btn=0x7f06001b;
        public static final int import_db_btn=0x7f060017;
        public static final int import_sql_btn=0x7f060019;
        public static final int odometer_edit=0x7f06000e;
        public static final int price_edit=0x7f06000c;
        public static final int save_btn=0x7f060011;
        public static final int stats_amount_average=0x7f06002d;
        public static final int stats_amount_average_cost=0x7f06002e;
        public static final int stats_amount_maximum=0x7f060032;
        public static final int stats_amount_maximum_cost=0x7f06002f;
        public static final int stats_amount_minimum=0x7f060031;
        public static final int stats_amount_minimum_cost=0x7f060030;
        public static final int stats_amount_running=0x7f06002c;
        public static final int stats_distance_average=0x7f060020;
        public static final int stats_distance_maximum=0x7f060021;
        public static final int stats_distance_minimum=0x7f060022;
        public static final int stats_distance_running=0x7f06001f;
        public static final int stats_economy_average=0x7f060024;
        public static final int stats_economy_maximum=0x7f060025;
        public static final int stats_economy_minimum=0x7f060026;
        public static final int stats_economy_running=0x7f060023;
        public static final int stats_price_average=0x7f060029;
        public static final int stats_price_latest=0x7f060027;
        public static final int stats_price_maximum=0x7f06002a;
        public static final int stats_price_minimum=0x7f06002b;
        public static final int stats_price_running=0x7f060028;
        public static final int stats_vehicle_spinner=0x7f06001e;
        public static final int vehicle_add=0x7f060006;
        public static final int vehicle_edit_make=0x7f060008;
        public static final int vehicle_edit_model=0x7f060009;
        public static final int vehicle_edit_save_btn=0x7f06000b;
        public static final int vehicle_edit_title=0x7f06000a;
        public static final int vehicle_edit_year=0x7f060007;
        public static final int vehicle_make=0x7f060003;
        public static final int vehicle_model=0x7f060004;
        public static final int vehicle_spinner=0x7f060010;
        public static final int vehicle_title=0x7f060005;
        public static final int vehicle_year=0x7f060002;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int add_vehicle=0x7f030001;
        public static final int edit_vehicle=0x7f030002;
        public static final int fillup=0x7f030003;
        public static final int graphs=0x7f030004;
        public static final int help=0x7f030005;
        public static final int history=0x7f030006;
        public static final int importexport=0x7f030007;
        public static final int main=0x7f030008;
        public static final int statistics=0x7f030009;
        public static final int vehicles=0x7f03000a;
    }
    public static final class string {
        public static final int about=0x7f040015;
        public static final int add_fillup=0x7f040006;
        public static final int app_name=0x7f040000;
        public static final int app_version=0x7f040001;
        public static final int author=0x7f040016;
        public static final int cancel_changes=0x7f04000d;
        public static final int close=0x7f040014;
        public static final int confirm_delete=0x7f04000e;
        public static final int contact=0x7f040017;
        public static final int csv_file=0x7f040049;
        public static final int custom_date=0x7f040005;
        public static final int delete=0x7f04000b;
        public static final int edit_fillup=0x7f04000c;
        public static final int error=0x7f04004a;
        public static final int error_amount=0x7f04004c;
        public static final int error_cost=0x7f04004b;
        public static final int error_exporting_data=0x7f04003a;
        public static final int error_importing_data=0x7f040046;
        public static final int error_mileage=0x7f04004d;
        public static final int export_finished=0x7f04003b;
        public static final int export_finished_msg=0x7f04003c;
        public static final int export_header=0x7f040039;
        public static final int exporting=0x7f04003d;
        public static final int exporting_title=0x7f04003e;
        public static final int fillup=0x7f040007;
        public static final int fillup_history=0x7f040008;
        public static final int gallons=0x7f040003;
        public static final int graphs=0x7f040009;
        public static final int help=0x7f04004e;
        public static final int help_export_csv=0x7f040054;
        public static final int help_export_db=0x7f040053;
        public static final int help_export_sql=0x7f040055;
        public static final int help_fillup_edit=0x7f040061;
        public static final int help_fillup_new=0x7f04005d;
        public static final int help_history=0x7f04005f;
        public static final int help_import_csv=0x7f040051;
        public static final int help_import_db=0x7f040050;
        public static final int help_import_sql=0x7f040052;
        public static final int help_title_fillup_edit=0x7f040060;
        public static final int help_title_fillup_new=0x7f04005c;
        public static final int help_title_history=0x7f04005e;
        public static final int help_title_import_export=0x7f04004f;
        public static final int help_title_vehicle_add=0x7f04005a;
        public static final int help_title_vehicle_edit=0x7f040058;
        public static final int help_title_vehicles=0x7f040056;
        public static final int help_vehicle_add=0x7f04005b;
        public static final int help_vehicle_edit=0x7f040059;
        public static final int help_vehicles=0x7f040057;
        public static final int history_description=0x7f040013;
        public static final int history_text1=0x7f04001a;
        public static final int history_text2=0x7f04001b;
        public static final int import_csv=0x7f040043;
        public static final int import_db=0x7f040041;
        public static final int import_done=0x7f040044;
        public static final int import_done_msg=0x7f040045;
        public static final int import_export=0x7f040038;
        public static final int import_header=0x7f040040;
        public static final int import_sql=0x7f040042;
        public static final int importing_title=0x7f04003f;
        public static final int no=0x7f040010;
        public static final int odometer=0x7f040004;
        public static final int ok=0x7f040011;
        public static final int price_per_gallon=0x7f040002;
        public static final int save_changes=0x7f04000a;
        public static final int sql_file=0x7f040048;
        public static final int sqlite=0x7f040047;
        public static final int statistics=0x7f040012;
        public static final int stats_amount_average=0x7f040032;
        public static final int stats_amount_average_cost=0x7f040035;
        public static final int stats_amount_maximum=0x7f040034;
        public static final int stats_amount_maximum_cost=0x7f040037;
        public static final int stats_amount_minimum=0x7f040033;
        public static final int stats_amount_minimum_cost=0x7f040036;
        public static final int stats_amount_running=0x7f040031;
        public static final int stats_default=0x7f040023;
        public static final int stats_distance_average=0x7f040025;
        public static final int stats_distance_maximum=0x7f040026;
        public static final int stats_distance_minimum=0x7f040027;
        public static final int stats_distance_running=0x7f040024;
        public static final int stats_economy_average=0x7f040029;
        public static final int stats_economy_maximum=0x7f04002b;
        public static final int stats_economy_minimum=0x7f04002a;
        public static final int stats_economy_running=0x7f040028;
        public static final int stats_price_average=0x7f04002e;
        public static final int stats_price_latest=0x7f04002d;
        public static final int stats_price_maximum=0x7f040030;
        public static final int stats_price_minimum=0x7f04002f;
        public static final int stats_price_running=0x7f04002c;
        public static final int today=0x7f040019;
        public static final int vehicle_add=0x7f040021;
        public static final int vehicle_make=0x7f04001d;
        public static final int vehicle_model=0x7f04001e;
        public static final int vehicle_save=0x7f040022;
        public static final int vehicle_title=0x7f040020;
        public static final int vehicle_year=0x7f04001f;
        public static final int vehicles=0x7f04001c;
        public static final int website=0x7f040018;
        public static final int yes=0x7f04000f;
    }
    public static final class style {
        public static final int LabelText=0x7f050002;
        public static final int StatisticText=0x7f050001;
        public static final int Theme=0x7f050000;
    }
}
